### ISSUE TITLE
Broadcast not working

### ISSUE THREAD

**Issue by DaAwesomeRazor** [sitegui/nodejs-websocket#28]
My Code:
```js
var ws = require("nodejs-websocket")


var server = ws.createServer(function (conn) {
    console.log("New connection")
    conn.on("text", function (str) {
        //console.log("Received "+str)
		 obj = JSON.parse(str);
         
		 
		 x = obj.x
		 y = obj.y
		 server = obj.server
		 cells = obj.cells
		 color = obj.color
		 nick = obj.nick
		 
		
		 playerData1 = JSON.stringify({x: x, y: y, server: server, cells: cells, color: color, nick: nick});
		 console.log(playerData1);
		 conn.send(playerData1)
		broadcast(playerData1);
    })
	
	
	
    conn.on("close", function (code, reason) {
        console.log("Connection closed")
    })
	
	
	

}).listen(8001)


function broadcast(str) {
	server.connections.forEach(function (conn) {
		conn.sendText(str)
	})
}

```

the error: 

TypeError: Cannot read property 'forEach' of undefined
    at broadcast (C:\Users\shzd1\Desktop\Minimap Server\server.js:38:20)
    at Connection.<anonymous> (C:\Users\shzd1\Desktop\Minimap Server\server.js:22:4)
    at emitOne (events.js:77:13)
    at Connection.emit (events.js:169:7)
    at Connection.processFrame (C:\Users\shzd1\Desktop\Minimap Server\node_modules\nodejs-websocket\Connection.js:558:9)
    at Connection.extractFrame (C:\Users\shzd1\Desktop\Minimap Server\node_modules\nodejs-websocket\Connection.js:499:14)
    at Connection.doRead (C:\Users\shzd1\Desktop\Minimap Server\node_modules\nodejs-websocket\Connection.js:239:23)
    at Socket.<anonymous> (C:\Users\shzd1\Desktop\Minimap Server\node_modules\nodejs-websocket\Connection.js:55:8)
    at emitNone (events.js:67:13)
    at Socket.emit (events.js:166:7)

**Comment by sitegui** [comment]
I couldn't reproduce this error. It may be in some other part of the code
